### ISSUE TITLE
Asus zenbook ux305LA need help

### ISSUE THREAD

**Issue by k-matti** [mikhail-m1/illuminanced#10]
Hi,
I tried run command:
`sudo watch cat /sys/bus/acpi/devices/ACPI0008\:00/iio\:device0/in_illuminance_raw`
but get:
`cat: '/sys/bus/acpi/devices/ACPI0008:00/iio:device0/in_illuminance_raw': No such file or directory`

Tried to install als driver but still no success

I am using ubuntu 20.04

**Comment by mikhail-m1** [comment]
I have ux305la and Ubuntu 20.04 and all works without external driver, please run and provide output:
```
lsmod | grep acpi
ls /sys/bus/acpi/devices/ACPI*
```

**Comment by k-matti** [comment]
Thanks for answer.
These are outputs:

![Screenshot from 2020-06-02 08-51-47](https://user-images.githubusercontent.com/66017397/83489277-799fc500-a4ae-11ea-894b-233164f3d8b3.png)
![Screenshot from 2020-06-02 08-52-29](https://user-images.githubusercontent.com/66017397/83489282-7ad0f200-a4ae-11ea-89c7-d3e46c84c0d9.png)

**Comment by mikhail-m1** [comment]
interesting, looks like `iio:device0` was removed and all files just put to parent directory, please provide output for `uname -a` and I will check my kernel version. Also can you try to run `sudo watch cat /sys/bus/acpi/devices/ACPI0008\:00/raw_value`

**Comment by k-matti** [comment]
`Linux krystian-ubuntu 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`
`sudo watch cat /sys/bus/acpi/devices/ACPI0008\:00/raw_value` gives me always 0

Maybe the problem is because I was playing with:
https://github.com/danieleds/als and
https://github.com/danieleds/Asus-Zenbook-Ambient-Light-Sensor-Controller

**Comment by mikhail-m1** [comment]
> Maybe the problem is because I was playing with:
> https://github.com/danieleds/als and

yeah, try remove als driver and check, I have 5.4.0-29, but I don't think it's related. 

you can check which driver is providing ACPI0008 by `ls /sys/bus/acpi/drivers/*`

**Comment by k-matti** [comment]
`ls /sys/bus/acpi/drivers/*` gives me this:

![image](https://user-images.githubusercontent.com/66017397/83547758-fb214280-a502-11ea-99d9-117df5b5ec2b.png)

Can you tell me how to remove als driver?

**Comment by mikhail-m1** [comment]
yeah, it's als, try `sudo rmmod als` and maybe `sudo rmmod acpi_als && modprobe acpi_als`

**Comment by k-matti** [comment]
ok so I use `sudo rmmod als` to remove als but `sudo rmmod acpi_als ` gives me `rmmod: ERROR: Module acpi_als is not currently loaded`
After `sudo modprobe acpi_als` it is working now :dancers: 

Thanks for helping

**Comment by k-matti** [comment]
@mikhail-m1 
One more thing: after every restart I have to run `sudo rmmod als && sudo rmmod acpi_als && sudo modprobe acpi_als` again to make your script works. Do you know how to make it permanent?

**Comment by mikhail-m1** [comment]
I don't remember how to remove driver correctly, but you can try just to remove file, it should be somewhere in /lib or wait for next kernel update.

**Comment by CapSel** [comment]
You can put a file in /etc/modprobe.d - call it something.conf (.conf part is important). Place there line:
`blacklist als`
After that rebuild your initrd image - every distro has it's own way.
Or you can try rebooting.
