### ISSUE TITLE
HP ZBook 17 G5 (4QH25EA#BCM) service does not load

### ISSUE THREAD

**Issue by mcDandy** [mikhail-m1/illuminanced#6]
output from systemcl service

● illuminanced.service - Ambient light monitoring Service
   Loaded: loaded (/etc/systemd/system/illuminanced.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-04-03 13:43:14 CEST; 5min ago
     Docs: https://github.com/mikhail-m1/illuminanced
  Process: 21951 ExecStart=/usr/local/sbin/illuminanced (code=exited, status=5)

dub 03 13:43:14 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Service RestartSec=100ms expire
dub 03 13:43:14 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Scheduled restart job, restart 
dub 03 13:43:14 daniel-HP-ZBook-17-G5 systemd[1]: Stopped Ambient light monitoring Service.
dub 03 13:43:14 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Start request repeated too quic
dub 03 13:43:14 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Failed with result 'exit-code'.
dub 03 13:43:14 daniel-HP-ZBook-17-G5 systemd[1]: Failed to start Ambient light monitoring Service.

output from jurnalctl e

-- 
-- Unit illuminanced.service has failed.
-- 
-- The result is RESULT.
dub 03 13:50:53 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Service RestartSec=100ms expire
dub 03 13:50:53 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Scheduled restart job, restart 
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Automatic restarting of the unit illuminanced.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
dub 03 13:50:53 daniel-HP-ZBook-17-G5 systemd[1]: Stopped Ambient light monitoring Service.
-- Subject: Unit illuminanced.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit illuminanced.service has finished shutting down.
dub 03 13:50:53 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Start request repeated too quic
dub 03 13:50:53 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Failed with result 'exit-code'.
dub 03 13:50:53 daniel-HP-ZBook-17-G5 systemd[1]: Failed to start Ambient light monitoring Service.
-- Subject: Unit illuminanced.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Unit illuminanced.service has failed.
-- 
-- The result is RESULT.

**Comment by mikhail-m1** [comment]
Could you please run it from command line in debug mode and provide output log
`sudo /usr/local/sbin/illumninanced -d`

**Comment by mcDandy** [comment]
It says command not found. What is the debug mode?
herčes output 
```
daniel@daniel-HP-ZBook-17-G5:/$ sudo /usr/local/sbin/illumninanced -d
sudo: /usr/local/sbin/illumninanced: příkaz nenalezen
```
but it exist 
```
daniel@daniel-HP-ZBook-17-G5:/usr/local/sbin$ ls
illuminanced
```
oh its iluminaced not uilumninaced

shows nothing

**Comment by mikhail-m1** [comment]
sorry `sudo /usr/local/sbin/illuminanced -d`

**Comment by mcDandy** [comment]
It immediately falls back to command prompt. Does not show anything. I will
rerun it when will get home from school in few hours.

Dne st 10. dub 2019 22:06 uživatel Mikhail Modin <notifications@github.com>
napsal:

**Comment by mcDandy** [comment]
is it somehow related to this bug?
https://bugs.launchpad.net/ubuntu/+source/upower/+bug/1823134

**Comment by mikhail-m1** [comment]
I thinks there is another path to the file with the illuminance or may be it doen't exit at all. I cannot help with it especially if you cannot run commands with sudo.

**Comment by mcDandy** [comment]
Can run it, but response from this cmd is blank.

Dne čt 2. kvě 2019 20:35 uživatel Mikhail Modin <notifications@github.com>
napsal:

**Comment by mcDandy** [comment]
For example sudo apt... works fine.

Dne so 4. kvě 2019 8:36 uživatel Daniel Martinek <danda.martinek@gmail.com>
napsal:

**Comment by mcDandy** [comment]
might have to be caused by


dub 10 23:09:55 daniel-HP-ZBook-17-G5 systemd[1]: Started Set the CPU Frequency Scaling governor.
dub 10 23:09:55 daniel-HP-ZBook-17-G5 systemd[1]: Reached target Login Prompts.
dub 10 23:09:55 daniel-HP-ZBook-17-G5 gpu-manager[1376]: Error: can't open /lib/modules/4.18.0-17-generic/updates/dkms
dub 10 23:09:55 daniel-HP-ZBook-17-G5 systemd-logind[1132]: Watching system buttons on /dev/input/event4 (AT Translated Set 2 keyboard)
dub 10 23:09:55 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: Found user 'avahi' (UID 119) and group 'avahi' (GID 126).
dub 10 23:09:55 daniel-HP-ZBook-17-G5 illuminanced[1225]: Cannot read file `/sys/class/backlight/intel_backlight/max_brightness`: No such file or directory (os error 2)
dub 10 23:09:55 daniel-HP-ZBook-17-G5 systemd[1]: Starting Snappy daemon...
dub 10 23:09:55 daniel-HP-ZBook-17-G5 systemd[1]: Started Raise network interfaces.
dub 10 23:09:55 daniel-HP-ZBook-17-G5 systemd[1]: Started Discard unused blocks.
dub 10 23:09:55 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Control process exited, code=exited status=5
dub 10 23:09:55 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Failed with result 'exit-code'.
dub 10 23:09:55 daniel-HP-ZBook-17-G5 systemd[1]: Failed to start Ambient light monitoring Service.
dub 10 23:09:55 daniel-HP-ZBook-17-G5 systemd[1]: Started Switcheroo Control Proxy service.
dub 10 23:09:55 daniel-HP-ZBook-17-G5 systemd[1]: Started Restore /etc/resolv.conf if the system crashed before the ppp link was shut down.
dub 10 23:09:55 daniel-HP-ZBook-17-G5 ModemManager[1232]: <info>  ModemManager (version 1.8.2) starting in system bus...
dub 10 23:09:56 daniel-HP-ZBook-17-G5 dbus-daemon[1367]: dbus[1367]: Unknown group "power" in message bus configuration file
dub 10 23:09:56 daniel-HP-ZBook-17-G5 acpid[1322]: starting up with netlink and the input layer
dub 10 23:09:57 daniel-HP-ZBook-17-G5 dbus-daemon[1367]: [system] AppArmor D-Bus mediation is enabled
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: Started Detect the available GPUs and deal with any system changes.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Service RestartSec=100ms expired, scheduling restart.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Scheduled restart job, restart counter is at 1.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 wpa_supplicant[1375]: Successfully initialized wpa_supplicant
dub 10 23:09:57 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: Successfully dropped root privileges.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: avahi-daemon 0.7 starting up.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: Started Login Service.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: Started Bluetooth service.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: Started Thermal Daemon Service.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: Started WPA supplicant.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 rsyslogd[1256]: imuxsock: Acquired UNIX socket '/run/systemd/journal/syslog' (fd 3) from systemd.  [v8.32.0]
dub 10 23:09:57 daniel-HP-ZBook-17-G5 rsyslogd[1256]: rsyslogd's groupid changed to 108
dub 10 23:09:57 daniel-HP-ZBook-17-G5 grub-common[1228]:  * Recording successful boot for GRUB
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: Started System Logging Service.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 apport[1327]:  * Starting automatic crash report generation: apport
dub 10 23:09:57 daniel-HP-ZBook-17-G5 rsyslogd[1256]: rsyslogd's userid changed to 103
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: Started IIO Sensor Proxy service.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 rsyslogd[1256]:  [origin software="rsyslogd" swVersion="8.32.0" x-pid="1256" x-info="http://www.rsyslog.com"] start
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: Reached target Bluetooth.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: Stopped Ambient light monitoring Service.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: Starting Ambient light monitoring Service...
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: Started Avahi mDNS/DNS-SD Stack.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: Successfully called chroot().
dub 10 23:09:57 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: Successfully dropped remaining capabilities.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: Started Make remote CUPS printers available locally.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 illuminanced[1557]: Cannot read file `/sys/class/backlight/intel_backlight/max_brightness`: No such file or directory (os error 2)
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Control process exited, code=exited status=5
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Failed with result 'exit-code'.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 systemd[1]: Failed to start Ambient light monitoring Service.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: No service file found in /etc/avahi/services.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: Joining mDNS multicast group on interface lo.IPv6 with address ::1.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: New relevant interface lo.IPv6 for mDNS.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: New relevant interface lo.IPv4 for mDNS.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: Network interface enumeration completed.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: Registering new address record for ::1 on lo.*.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: Registering new address record for 127.0.0.1 on lo.IPv4.
dub 10 23:09:57 daniel-HP-ZBook-17-G5 bluetoothd[1245]: Starting SDP server
dub 10 23:09:57 daniel-HP-ZBook-17-G5 thermald[1251]: 22 CPUID levels; family:model:stepping 0x6:9e:a (6:158:10)
dub 10 23:09:57 daniel-HP-ZBook-17-G5 thermald[1251]: Polling mode is enabled: 4
dub 10 23:09:57 daniel-HP-ZBook-17-G5 kernel: Bluetooth: BNEP (Ethernet Emulation) ver 1.3
dub 10 23:09:57 daniel-HP-ZBook-17-G5 kernel: Bluetooth: BNEP filters: protocol multicast
dub 10 23:09:57 daniel-HP-ZBook-17-G5 kernel: Bluetooth: BNEP socket layer initialized
dub 10 23:09:57 daniel-HP-ZBook-17-G5 dbus-daemon[1367]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' r
dub 10 23:09:57 daniel-HP-ZBook-17-G5 bluetoothd[1245]: Bluetooth management interface 1.14 initialized
dub 10 23:09:57 daniel-HP-ZBook-17-G5 acpid[1322]: 8 rules loaded
dub 10 23:09:57 daniel-HP-ZBook-17-G5 acpid[1322]: waiting for events: event logging is off
dub 10 23:09:57 daniel-HP-ZBook-17-G5 apport[1327]:    ...done.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 avahi-daemon[1238]: Server startup complete. Host name is daniel-HP-ZBook-17-G5.local. Local service cookie is 3823168498.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 dbus-daemon[1367]: [system] Activating via systemd: service name='org.freedesktop.PolicyKit1' unit='polkit.service' requested by ':1.10' (ui
dub 10 23:09:58 daniel-HP-ZBook-17-G5 thermald[1251]: sysfs read failed constraint_0_max_power_uw
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Started LSB: automatic crash report generation.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 bluetoothd[1245]: Failed to set mode: Blocked through rfkill (0x12)
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Service RestartSec=100ms expired, scheduling restart.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 illuminanced[1614]: Cannot read file `/sys/class/backlight/intel_backlight/max_brightness`: No such file or directory (os error 2)
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Scheduled restart job, restart counter is at 2.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Starting Authorization Manager...
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Stopped Ambient light monitoring Service.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Starting Ambient light monitoring Service...
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Starting Hostname Service...
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Control process exited, code=exited status=5
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Failed with result 'exit-code'.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Failed to start Ambient light monitoring Service.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 grub-common[1228]:    ...done.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Started LSB: Record successful boot for GRUB.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 polkitd[1613]: started daemon version 0.105 using authority implementation `local' version `0.105'
dub 10 23:09:58 daniel-HP-ZBook-17-G5 dbus-daemon[1367]: [system] Successfully activated service 'org.freedesktop.PolicyKit1'
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Started Authorization Manager.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 accounts-daemon[1125]: started daemon version 0.6.45
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Started Accounts Service.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 NetworkManager[1374]: <info>  [1554930598.7492] NetworkManager (version 1.12.4) is starting... (for the first time)
dub 10 23:09:58 daniel-HP-ZBook-17-G5 NetworkManager[1374]: <info>  [1554930598.7493] Read config: /etc/NetworkManager/NetworkManager.conf (lib: 10-dns-resolved.conf, 20-connecti
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Started Network Manager.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 NetworkManager[1374]: <info>  [1554930598.7603] bus-manager: acquired D-Bus service "org.freedesktop.NetworkManager"
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Starting Network Manager Wait Online...
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Reached target Network.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Started Service for snap application docker.dockerd.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Starting OpenVPN service...
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Starting Permit User Sessions...
dub 10 23:09:58 daniel-HP-ZBook-17-G5 NetworkManager[1374]: <info>  [1554930598.7731] manager[0x5590de84f020]: monitoring kernel firmware directory '/lib/firmware'.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 NetworkManager[1374]: <info>  [1554930598.7731] monitoring ifupdown state file '/run/network/ifstate'.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 udisksd[1117]: failed to load module mdraid: libbd_mdraid.so.2: cannot open shared object file: No such file or directory
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Starting sndio audio and MIDI server...
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Started Unattended Upgrades Shutdown.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Service RestartSec=100ms expired, scheduling restart.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Scheduled restart job, restart counter is at 3.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Stopped Ambient light monitoring Service.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Starting Ambient light monitoring Service...
dub 10 23:09:58 daniel-HP-ZBook-17-G5 illuminanced[1726]: Cannot read file `/sys/class/backlight/intel_backlight/max_brightness`: No such file or directory (os error 2)
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Control process exited, code=exited status=5
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Failed with result 'exit-code'.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Failed to start Ambient light monitoring Service.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Started sndio audio and MIDI server.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Started OpenVPN service.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Started Permit User Sessions.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Starting Hold until boot process finishes up...
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Starting GNOME Display Manager...
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Started GNOME Display Manager.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Service RestartSec=100ms expired, scheduling restart.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Scheduled restart job, restart counter is at 4.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Stopped Ambient light monitoring Service.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Starting GNOME Display Manager...
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Started GNOME Display Manager.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Service RestartSec=100ms expired, scheduling restart.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Scheduled restart job, restart counter is at 4.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Stopped Ambient light monitoring Service.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Starting Ambient light monitoring Service...
dub 10 23:09:58 daniel-HP-ZBook-17-G5 illuminanced[1844]: Cannot read file `/sys/class/backlight/intel_backlight/max_brightness`: No such file or directory (os error 2)
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Control process exited, code=exited status=5
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Failed with result 'exit-code'.
dub 10 23:09:58 daniel-HP-ZBook-17-G5 systemd[1]: Failed to start Ambient light monitoring Service.
dub 10 23:09:59 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Service RestartSec=100ms expired, scheduling restart.
dub 10 23:09:59 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Scheduled restart job, restart counter is at 5.
dub 10 23:09:59 daniel-HP-ZBook-17-G5 systemd[1]: Stopped Ambient light monitoring Service.
dub 10 23:09:59 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Start request repeated too quickly.
dub 10 23:09:59 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: Failed with result 'exit-code'.
dub 10 23:09:59 daniel-HP-ZBook-17-G5 systemd[1]: Failed to start Ambient light monitoring Service.
dub 10 23:09:59 daniel-HP-ZBook-17-G5 rsyslogd[1256]:  [origin software="rsyslogd" swVersion="8.32.0" x-pid="1256" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
dub 10 23:09:59 daniel-HP-ZBook-17-G5 snapd[1452]: AppArmor status: apparmor is enabled and all features are available
dub 10 23:09:59 daniel-HP-ZBook-17-G5 udisksd[1117]: Failed to load the 'mdraid' libblockdev plugin

**Comment by mikhail-m1** [comment]
yes, looks like `/sys/class/backlight/intel_backlight/max_brightness` is not where I expected, could you  try to find it and fix path in the config file?

**Comment by mcDandy** [comment]
Sorry, but where is the config file? Did not find it in /etc

Dne po 17. čvn 2019 23:05 uživatel Mikhail Modin <notifications@github.com>
napsal:

**Comment by mikhail-m1** [comment]
should be in `/usr/local/etc/illuminanced.toml`

**Comment by mcDandy** [comment]
Forgot to test wil attempt hopefully tomorrow

**Comment by mcDandy** [comment]
Tryed to change the path to backlight, but with no success


● illuminanced.service - Ambient light monitoring Service
    Loaded: loaded (/etc/systemd/system/illuminanced.service; enabled; 
vendor preset: enabled)
    Active: failed (Result: exit-code) since Mon 2019-06-24 16:11:44 
CEST; 23s ago
      Docs: https://github.com/mikhail-m1/illuminanced
   Process: 15147 ExecStart=/usr/local/sbin/illuminanced (code=exited, 
status=8)

čen 24 16:11:44 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: 
Service RestartSec=100ms expired, scheduling restart.
čen 24 16:11:44 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: 
Scheduled restart job, restart counter is at 5.
čen 24 16:11:44 daniel-HP-ZBook-17-G5 systemd[1]: Stopped Ambient light 
monitoring Service.
čen 24 16:11:44 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: 
Start request repeated too quickly.
čen 24 16:11:44 daniel-HP-ZBook-17-G5 systemd[1]: illuminanced.service: 
Failed with result 'exit-code'.
čen 24 16:11:44 daniel-HP-ZBook-17-G5 systemd[1]: Failed to start 
Ambient light monitoring Service.

Path to backlight

max_backlight_file = "/sys/class/backlight/nvidia_0/max_brightness"
backlight_file = "/sys/class/backlight/nvidia_0/brightness"

Dne 21. 06. 19 v 23:28 Mikhail Modin napsal(a):

**Comment by mikhail-m1** [comment]
I cannot say why it doesn't start without logs, I need line with errors like this one
```
dub 10 23:09:55 daniel-HP-ZBook-17-G5 illuminanced[1225]: Cannot read file /sys/class/backlight/intel_backlight/max_brightness: No such file or directory (os error 2)
```

**Comment by bendardenne** [comment]
FYI on my ZBook 15 G6, I also need to change the path of the illuminance input to:

`/sys/bus/iio/devices/iio:device0/in_illuminance_raw`

You'll also need to change the thresholds as the sensor is giving numbers that are an order of magnitude larger than the example.
